[workspace]
members = [
    "moc3-example",
    "moc3-impressionism",
    "moc3-physicsview",
    "moc3-rs",
    "moc3-wgpu",
]
resolver = "2"

[workspace.dependencies]
binrw = "0.15.0"
bytemuck = "1.23.2"
glam = "0.30.5"
image = "0.25.6"
wgpu = "26.0.1"
winit = "0.30.12"
