[workspace]
members = [
    "moc3-example",
    "moc3-impressionism",
    "moc3-physicsview",
    "moc3-rs",
    "moc3-wgpu",
]
resolver = "2"

[workspace.dependencies]
binrw = "0.14.1"
bytemuck = "1.22.0"
glam = "0.29"
wgpu = "24.0.3"
winit = "0.30.9"
