[package]
name = "moc3-impressionism"
version = "0.1.0"
edition = "2021"

[dependencies]
glam = { workspace = true, features = ["bytemuck", "serde"] }
moc3-rs = { path = "../moc3-rs" }
serde = { version = "1.0.152", features = ["derive"] }
