[package]
name = "moc3-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
binrw = "0.14.1"
bytemuck = { workspace = true, features = ["extern_crate_alloc", "derive"] }
glam = { workspace = true, features = ["bytemuck"] }
indextree = "4.6.0"
modular-bitfield = "0.11.2"
thiserror = "1.0.48"

